name: End-to-end tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wait-for-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview With Bypass Protection
        uses: amerfarooq/wait-for-vercel-preview-and-bypass-protection@v1.0.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      # access preview url
      - run: echo ${{steps.waitFor200.outputs.url}}

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
