name: Run Cypress tests

on:
  push:
    branches:
      - main
      - "feature/*"

jobs:
  e2e-cypress:
    name: E2E Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
          environment: Preview

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ steps.waitForVercelPreview.outputs.url }}
